from django.urls import path, re_path
from . import views

app_name = 'booking'

urlpatterns = [
    path('', views.doctor_list, name='doctor_list'),
    path('signup/', views.doctor_signup, name='signup'),
    path('signup/verify/', views.verify_doctor_signup, name='verify_doctor_signup'),
    path('signup/secretary/', views.secretary_signup, name='secretary_signup'),
    path('signup/secretary/verify/', views.verify_secretary_signup, name='verify_secretary_signup'),
    path('doctor/<int:pk>/', views.doctor_detail, name='doctor_detail'),
    path('doctor/<int:pk>/book/<str:date>/', views.book_appointment, name='book_appointment'),
    path('verify/', views.verify_appointment, name='verify_appointment'),
    path('confirm/', views.confirm_payment, name='confirm_payment'),
    path('dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('availability/<int:pk>/edit/', views.edit_availability, name='edit_availability'),
    path('availability/<int:pk>/delete/', views.delete_availability, name='delete_availability'),
    path('availability/<int:pk>/toggle/', views.toggle_availability, name='toggle_availability'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    re_path(r'^secretary-panel/(?P<date>\d{4}-\d{2}-\d{2})?/?$', views.secretary_panel, name='secretary_panel'),
    re_path(r'^daily-patients/(?P<date>\d{4}-\d{2}-\d{2})?/?$', views.daily_patients, name='daily_patients'),
    path('patient-list/', views.patient_list, name='patient_list'),
    re_path(r'^secretary-payments/(?P<date>\d{4}-\d{2}-\d{2})?/?$', views.secretary_payments, name='secretary_payments'),
    path('expense/edit/<int:pk>/', views.edit_expense, name='edit_expense'),
    path('expense/delete/<int:pk>/', views.delete_expense, name='delete_expense'),
    re_path(r'^financial-report/(?:(?P<period>daily|monthly|yearly)/)?(?:(?P<date>\d{4}-\d{2}-\d{2})/)?$', views.financial_report, name='financial_report'),
    path('expense-balance/', views.expense_balance_report, name='expense_balance_report'),
    path('expense-balance/<str:description>/', views.expense_item_details, name='expense_item_details'),
    path('manage-day/<str:date>/', views.manage_day, name='manage_day'),
    path('payment/', views.payment_page, name='payment_page'),
    path('verify-payment/', views.verify_payment, name='verify_payment'),
    path('accounting-guide/', views.accounting_guide, name='accounting_guide'),
    path('export/patients/excel/', views.export_patients_to_excel, name='export_patients_to_excel'),
    path('export/expenses/excel/', views.export_expenses_to_excel, name='export_expenses_to_excel'),
    path('patient-login/', views.patient_login, name='patient_login'),
    path('patient-login/verify/', views.verify_patient_login, name='verify_patient_login'),
    path('patient-dashboard-entry/', views.patient_dashboard_entry, name='patient_dashboard_entry'),
    path('patient-logout/', views.patient_logout, name='patient_logout'),
    path('patient-dashboard/', views.patient_dashboard, name='patient_dashboard'),
]