# Generated by Django 5.2.7 on 2025-10-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="payment_method",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "کارت خوان"),
                    (2, "نقدی"),
                    (3, "کارت به کارت"),
                    (4, "رایگان"),
                ],
                null=True,
                verbose_name="نوع پرداخت",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service_description",
            field=models.CharField(
                default="حق ویزیت", max_length=255, verbose_name="شرح خدمات"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="visit_fee_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="مبلغ ویزیت دریافتی",
            ),
        ),
    ]
