# Generated by Django 5.2.7 on 2025-10-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_appointment_payment_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="تاریخ")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="شرح هزینه/پرداخت"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        verbose_name="مبلغ (پرداخت: مثبت, هزینه: منفی)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="booking.doctorprofile",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "هزینه/پرداخت روزانه",
                "verbose_name_plural": "هزینه\u200cها و پرداخت\u200cهای روزانه",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
