# Generated by Django 5.2.7 on 2025-10-11 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_appointment_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlotException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_slot",
                    models.DateTimeField(verbose_name="بازه زمانی لغو شده"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="booking.doctorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "استثناء زمانی",
                "verbose_name_plural": "استثناهای زمانی",
                "unique_together": {("doctor", "datetime_slot")},
            },
        ),
    ]
