# Generated by Django 5.2.7 on 2025-10-12 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_timeslotexception"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyexpense",
            name="date",
            field=models.DateField(default=datetime.date.today, verbose_name="تاریخ"),
        ),
    ]
