# Generated by Django 5.2.7 on 2025-10-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_alter_dailyexpense_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="آدرس مطب"),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="شماره تلفن مطب"
            ),
        ),
    ]
