# Generated by Django 5.2.7 on 2025-10-19 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_doctorprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("TAMIN", "تامین اجتماعی"),
                    ("SALAMAT", "سلامت"),
                    ("KHADAMAT", "خدمات درمانی"),
                    ("ARTESH", "ارتش"),
                    ("AZAD", "آزاد"),
                ],
                default="AZAD",
                max_length=10,
                verbose_name="نوع بیمه",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_national_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="کد ملی بیمار"
            ),
        ),
        migrations.CreateModel(
            name="InsuranceFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("TAMIN", "تامین اجتماعی"),
                            ("SALAMAT", "سلامت"),
                            ("KHADAMAT", "خدمات درمانی"),
                            ("ARTESH", "ارتش"),
                            ("AZAD", "آزاد"),
                        ],
                        max_length=10,
                        verbose_name="نوع بیمه",
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="مبلغ ویزیت"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_fees",
                        to="booking.doctorprofile",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "هزینه بیمه",
                "verbose_name_plural": "هزینه\u200cهای بیمه",
                "unique_together": {("doctor", "insurance_type")},
            },
        ),
    ]
