# Generated by Django 5.2.7 on 2025-10-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_appointment_insurance_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslotexception",
            name="is_cancellation",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="dailyexpense",
            name="amount",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="timeslotexception",
            name="datetime_slot",
            field=models.DateTimeField(verbose_name="بازه زمانی"),
        ),
    ]
