# Generated by Django 5.2.7 on 2025-11-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_timeslotexception_is_cancellation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="visit_fee",
            field=models.DecimalField(
                decimal_places=0,
                default=100000,
                max_digits=10,
                verbose_name="هزینه ویزیت آنلاین",
            ),
        ),
    ]
