# Generated by Django 5.2.8 on 2025-11-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_doctorprofile_visit_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("TAMIN", "تامین اجتماعی"),
                    ("KHADAMAT", "خدمات درمانی"),
                    ("ARTESH", "نیروی مسلح"),
                    ("AZAD", "آزاد"),
                ],
                default="AZAD",
                max_length=10,
                verbose_name="نوع بیمه",
            ),
        ),
        migrations.AlterField(
            model_name="insurancefee",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("TAMIN", "تامین اجتماعی"),
                    ("KHADAMAT", "خدمات درمانی"),
                    ("ARTESH", "نیروی مسلح"),
                    ("AZAD", "آزاد"),
                ],
                max_length=10,
                verbose_name="نوع بیمه",
            ),
        ),
    ]
