# Generated by Django 5.2.8 on 2025-11-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_alter_appointment_insurance_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="mobile_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="شماره موبایل"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("TAMIN", "بیمه تامین اجتماعی"),
                    ("KHADAMAT", "بیمه خدمات درمانی"),
                    ("MOSALAH", "بیمه نیروهای مسلح"),
                    ("AZAD", "آزاد"),
                ],
                default="AZAD",
                max_length=10,
                verbose_name="نوع بیمه",
            ),
        ),
        migrations.AlterField(
            model_name="insurancefee",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("TAMIN", "بیمه تامین اجتماعی"),
                    ("KHADAMAT", "بیمه خدمات درمانی"),
                    ("MOSALAH", "بیمه نیروهای مسلح"),
                    ("AZAD", "آزاد"),
                ],
                max_length=10,
                verbose_name="نوع بیمه",
            ),
        ),
    ]
