# Generated by Django 5.2.8 on 2025-11-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_doctorprofile_mobile_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="booking_days",
            field=models.PositiveIntegerField(
                default=45, verbose_name="تعداد روزهای نمایش نوبت"
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="secretary_card_number",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="شماره کارت منشی"
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="secretary_mobile",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="موبایل منشی"
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="secretary_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نام منشی"
            ),
        ),
    ]
