# Generated by Django 5.2.8 on 2025-11-19 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_doctorprofile_booking_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secretaries",
                to="booking.doctorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                    ("SECRETARY", "Secretary"),
                    ("ADMIN", "Admin"),
                ],
                default="PATIENT",
                max_length=10,
            ),
        ),
    ]
