# Generated by Django 5.2.8 on 2025-11-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_customuser_doctor_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="financial_settings_completed",
            field=models.BooleanField(
                default=False, verbose_name="تنظیمات مالی تکمیل شده"
            ),
        ),
    ]
