# Generated by Django 5.2.8 on 2025-11-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_doctorprofile_financial_settings_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="پرداخت شده"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_order_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="شناسه سفارش پرداخت"
            ),
        ),
    ]
