# Generated by Django 5.2.8 on 2025-11-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_appointment_is_paid_appointment_payment_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="is_paid",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="payment_order_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="شناسه یکتای پرداخت"
            ),
        ),
    ]
