# Generated by Django 5.2.8 on 2025-12-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_appointment_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='insurance_type',
            field=models.CharField(choices=[('TAMIN', 'تامین اجتماعی'), ('KHADAMAT', 'خدمات درمانی'), ('ARTESH', 'نیروی مسلح'), ('AZAD', 'آزاد')], default='AZAD', max_length=10, verbose_name='نوع بیمه'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='booking_days',
            field=models.PositiveIntegerField(default=30, verbose_name='تعداد روزهای نمایش نوبت'),
        ),
        migrations.AlterField(
            model_name='insurancefee',
            name='insurance_type',
            field=models.CharField(choices=[('TAMIN', 'تامین اجتماعی'), ('KHADAMAT', 'خدمات درمانی'), ('ARTESH', 'نیروی مسلح'), ('AZAD', 'آزاد')], max_length=10, verbose_name='نوع بیمه'),
        ),
    ]
