# Generated by Django 5.2.8 on 2025-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_appointment_insurance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'رزرو شده'), (2, 'تکمیل شده'), (3, 'لغو شده'), (4, 'در انتظار پرداخت')], default=4),
        ),
    ]
