# Generated by Django 5.2.8 on 2025-12-12 16:16

import booking.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0019_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", booking.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email",
        ),
    ]
